#spring:
#  datasource:
#    username: postgres
#    password: password
#    url: jdbc:postgresql://localhost:5432/jobTrackApiDb
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    properties.hibernate.dialect: org.hibernate.dialect.PostgresPlusDialect
#    open-in-view: false
#    generate-ddl: true
